/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedStudentRouteRouteImport } from './routes/_protected/_student/route'
import { Route as GuestAuthRouteRouteImport } from './routes/_guest.auth/route'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as GuestAuthIndexRouteImport } from './routes/_guest.auth/index'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminReportsRouteImport } from './routes/_protected/admin/reports'
import { Route as ProtectedAdminContentRouteImport } from './routes/_protected/admin/content'
import { Route as GuestAuthRegisterRouteImport } from './routes/_guest.auth/register'
import { Route as GuestAuthLoginRouteImport } from './routes/_guest.auth/login'
import { Route as ProtectedStudentRoadmapIndexRouteImport } from './routes/_protected/_student/roadmap/index'
import { Route as ProtectedStudentLeaderboardIndexRouteImport } from './routes/_protected/_student/leaderboard/index'
import { Route as ProtectedStudentHistoryIndexRouteImport } from './routes/_protected/_student/history/index'
import { Route as ProtectedStudentDashboardIndexRouteImport } from './routes/_protected/_student/dashboard/index'
import { Route as ProtectedAdminLessonsLessonIdRouteImport } from './routes/_protected/admin/lessons/$lessonId'
import { Route as ProtectedStudentRoadmapModuleIdRouteImport } from './routes/_protected/_student/roadmap/$moduleId'
import { Route as ProtectedStudentLessonLessonIdRouteImport } from './routes/_protected/_student/lesson/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/_protected/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedStudentRouteRoute = ProtectedStudentRouteRouteImport.update({
  id: '/_protected/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAuthRouteRoute = GuestAuthRouteRouteImport.update({
  id: '/_guest/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const GuestAuthIndexRoute = GuestAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestAuthRouteRoute,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminReportsRoute = ProtectedAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminContentRoute = ProtectedAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const GuestAuthRegisterRoute = GuestAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestAuthRouteRoute,
} as any)
const GuestAuthLoginRoute = GuestAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestAuthRouteRoute,
} as any)
const ProtectedStudentRoadmapIndexRoute =
  ProtectedStudentRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedStudentLeaderboardIndexRoute =
  ProtectedStudentLeaderboardIndexRouteImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedStudentHistoryIndexRoute =
  ProtectedStudentHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedStudentDashboardIndexRoute =
  ProtectedStudentDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedAdminLessonsLessonIdRoute =
  ProtectedAdminLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedStudentRoadmapModuleIdRoute =
  ProtectedStudentRoadmapModuleIdRouteImport.update({
    id: '/roadmap/$moduleId',
    path: '/roadmap/$moduleId',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedStudentLessonLessonIdRoute =
  ProtectedStudentLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof GuestAuthRouteRouteWithChildren
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/auth/login': typeof GuestAuthLoginRoute
  '/auth/register': typeof GuestAuthRegisterRoute
  '/admin/content': typeof ProtectedAdminContentRoute
  '/admin/reports': typeof ProtectedAdminReportsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/auth/': typeof GuestAuthIndexRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/lesson/$lessonId': typeof ProtectedStudentLessonLessonIdRoute
  '/roadmap/$moduleId': typeof ProtectedStudentRoadmapModuleIdRoute
  '/admin/lessons/$lessonId': typeof ProtectedAdminLessonsLessonIdRoute
  '/dashboard/': typeof ProtectedStudentDashboardIndexRoute
  '/history/': typeof ProtectedStudentHistoryIndexRoute
  '/leaderboard/': typeof ProtectedStudentLeaderboardIndexRoute
  '/roadmap/': typeof ProtectedStudentRoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof GuestAuthLoginRoute
  '/auth/register': typeof GuestAuthRegisterRoute
  '/admin/content': typeof ProtectedAdminContentRoute
  '/admin/reports': typeof ProtectedAdminReportsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/auth': typeof GuestAuthIndexRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/lesson/$lessonId': typeof ProtectedStudentLessonLessonIdRoute
  '/roadmap/$moduleId': typeof ProtectedStudentRoadmapModuleIdRoute
  '/admin/lessons/$lessonId': typeof ProtectedAdminLessonsLessonIdRoute
  '/dashboard': typeof ProtectedStudentDashboardIndexRoute
  '/history': typeof ProtectedStudentHistoryIndexRoute
  '/leaderboard': typeof ProtectedStudentLeaderboardIndexRoute
  '/roadmap': typeof ProtectedStudentRoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest/auth': typeof GuestAuthRouteRouteWithChildren
  '/_protected/_student': typeof ProtectedStudentRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_guest/auth/login': typeof GuestAuthLoginRoute
  '/_guest/auth/register': typeof GuestAuthRegisterRoute
  '/_protected/admin/content': typeof ProtectedAdminContentRoute
  '/_protected/admin/reports': typeof ProtectedAdminReportsRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_guest/auth/': typeof GuestAuthIndexRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/_student/lesson/$lessonId': typeof ProtectedStudentLessonLessonIdRoute
  '/_protected/_student/roadmap/$moduleId': typeof ProtectedStudentRoadmapModuleIdRoute
  '/_protected/admin/lessons/$lessonId': typeof ProtectedAdminLessonsLessonIdRoute
  '/_protected/_student/dashboard/': typeof ProtectedStudentDashboardIndexRoute
  '/_protected/_student/history/': typeof ProtectedStudentHistoryIndexRoute
  '/_protected/_student/leaderboard/': typeof ProtectedStudentLeaderboardIndexRoute
  '/_protected/_student/roadmap/': typeof ProtectedStudentRoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/auth/login'
    | '/auth/register'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/'
    | '/admin/'
    | '/lesson/$lessonId'
    | '/roadmap/$moduleId'
    | '/admin/lessons/$lessonId'
    | '/dashboard/'
    | '/history/'
    | '/leaderboard/'
    | '/roadmap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/users'
    | '/auth'
    | '/admin'
    | '/lesson/$lessonId'
    | '/roadmap/$moduleId'
    | '/admin/lessons/$lessonId'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_guest/auth'
    | '/_protected/_student'
    | '/_protected/admin'
    | '/_guest/auth/login'
    | '/_guest/auth/register'
    | '/_protected/admin/content'
    | '/_protected/admin/reports'
    | '/_protected/admin/users'
    | '/_guest/auth/'
    | '/_protected/admin/'
    | '/_protected/_student/lesson/$lessonId'
    | '/_protected/_student/roadmap/$moduleId'
    | '/_protected/admin/lessons/$lessonId'
    | '/_protected/_student/dashboard/'
    | '/_protected/_student/history/'
    | '/_protected/_student/leaderboard/'
    | '/_protected/_student/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestAuthRouteRoute: typeof GuestAuthRouteRouteWithChildren
  ProtectedStudentRouteRoute: typeof ProtectedStudentRouteRouteWithChildren
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_student': {
      id: '/_protected/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/auth': {
      id: '/_guest/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof GuestAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_guest/auth/': {
      id: '/_guest/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof GuestAuthIndexRouteImport
      parentRoute: typeof GuestAuthRouteRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/reports': {
      id: '/_protected/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof ProtectedAdminReportsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/content': {
      id: '/_protected/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof ProtectedAdminContentRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_guest/auth/register': {
      id: '/_guest/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof GuestAuthRegisterRouteImport
      parentRoute: typeof GuestAuthRouteRoute
    }
    '/_guest/auth/login': {
      id: '/_guest/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof GuestAuthLoginRouteImport
      parentRoute: typeof GuestAuthRouteRoute
    }
    '/_protected/_student/roadmap/': {
      id: '/_protected/_student/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof ProtectedStudentRoadmapIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/_student/leaderboard/': {
      id: '/_protected/_student/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof ProtectedStudentLeaderboardIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/_student/history/': {
      id: '/_protected/_student/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof ProtectedStudentHistoryIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/_student/dashboard/': {
      id: '/_protected/_student/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedStudentDashboardIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/admin/lessons/$lessonId': {
      id: '/_protected/admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof ProtectedAdminLessonsLessonIdRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/_student/roadmap/$moduleId': {
      id: '/_protected/_student/roadmap/$moduleId'
      path: '/roadmap/$moduleId'
      fullPath: '/roadmap/$moduleId'
      preLoaderRoute: typeof ProtectedStudentRoadmapModuleIdRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/_student/lesson/$lessonId': {
      id: '/_protected/_student/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof ProtectedStudentLessonLessonIdRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
  }
}

interface GuestAuthRouteRouteChildren {
  GuestAuthLoginRoute: typeof GuestAuthLoginRoute
  GuestAuthRegisterRoute: typeof GuestAuthRegisterRoute
  GuestAuthIndexRoute: typeof GuestAuthIndexRoute
}

const GuestAuthRouteRouteChildren: GuestAuthRouteRouteChildren = {
  GuestAuthLoginRoute: GuestAuthLoginRoute,
  GuestAuthRegisterRoute: GuestAuthRegisterRoute,
  GuestAuthIndexRoute: GuestAuthIndexRoute,
}

const GuestAuthRouteRouteWithChildren = GuestAuthRouteRoute._addFileChildren(
  GuestAuthRouteRouteChildren,
)

interface ProtectedStudentRouteRouteChildren {
  ProtectedStudentLessonLessonIdRoute: typeof ProtectedStudentLessonLessonIdRoute
  ProtectedStudentRoadmapModuleIdRoute: typeof ProtectedStudentRoadmapModuleIdRoute
  ProtectedStudentDashboardIndexRoute: typeof ProtectedStudentDashboardIndexRoute
  ProtectedStudentHistoryIndexRoute: typeof ProtectedStudentHistoryIndexRoute
  ProtectedStudentLeaderboardIndexRoute: typeof ProtectedStudentLeaderboardIndexRoute
  ProtectedStudentRoadmapIndexRoute: typeof ProtectedStudentRoadmapIndexRoute
}

const ProtectedStudentRouteRouteChildren: ProtectedStudentRouteRouteChildren = {
  ProtectedStudentLessonLessonIdRoute: ProtectedStudentLessonLessonIdRoute,
  ProtectedStudentRoadmapModuleIdRoute: ProtectedStudentRoadmapModuleIdRoute,
  ProtectedStudentDashboardIndexRoute: ProtectedStudentDashboardIndexRoute,
  ProtectedStudentHistoryIndexRoute: ProtectedStudentHistoryIndexRoute,
  ProtectedStudentLeaderboardIndexRoute: ProtectedStudentLeaderboardIndexRoute,
  ProtectedStudentRoadmapIndexRoute: ProtectedStudentRoadmapIndexRoute,
}

const ProtectedStudentRouteRouteWithChildren =
  ProtectedStudentRouteRoute._addFileChildren(
    ProtectedStudentRouteRouteChildren,
  )

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminContentRoute: typeof ProtectedAdminContentRoute
  ProtectedAdminReportsRoute: typeof ProtectedAdminReportsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminLessonsLessonIdRoute: typeof ProtectedAdminLessonsLessonIdRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminContentRoute: ProtectedAdminContentRoute,
  ProtectedAdminReportsRoute: ProtectedAdminReportsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminLessonsLessonIdRoute: ProtectedAdminLessonsLessonIdRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestAuthRouteRoute: GuestAuthRouteRouteWithChildren,
  ProtectedStudentRouteRoute: ProtectedStudentRouteRouteWithChildren,
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
