-- CreateEnum
CREATE TYPE "QuestionType" AS ENUM ('MULTIPLE_CHOICE', 'CALCULATION_INPUT', 'COMMAND_TYPING', 'SORTING', 'MATCHING', 'IMAGE_LABELING');

-- AlterTable
ALTER TABLE "questions" ADD COLUMN     "type" "QuestionType" NOT NULL DEFAULT 'MULTIPLE_CHOICE';
