/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/_student'
import { Route as AuthenticatedStudentRoadmapRouteImport } from './routes/_authenticated/_student/roadmap'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/_student/profile'
import { Route as AuthenticatedStudentLessonRouteImport } from './routes/_authenticated/_student/lesson'
import { Route as AuthenticatedStudentLeaderboardRouteImport } from './routes/_authenticated/_student/leaderboard'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated/_student/history'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/_student/dashboard'
import { Route as AuthenticatedStudentRoadmapIndexRouteImport } from './routes/_authenticated/_student/roadmap/index'
import { Route as AuthenticatedStudentRoadmapModuleIdRouteImport } from './routes/_authenticated/_student/roadmap/$moduleId'
import { Route as AuthenticatedStudentLessonLessonIdRouteImport } from './routes/_authenticated/_student/lesson/$lessonId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoadmapRoute =
  AuthenticatedStudentRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentLessonRoute =
  AuthenticatedStudentLessonRouteImport.update({
    id: '/lesson',
    path: '/lesson',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentLeaderboardRoute =
  AuthenticatedStudentLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentRoadmapIndexRoute =
  AuthenticatedStudentRoadmapIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoadmapRoute,
  } as any)
const AuthenticatedStudentRoadmapModuleIdRoute =
  AuthenticatedStudentRoadmapModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedStudentRoadmapRoute,
  } as any)
const AuthenticatedStudentLessonLessonIdRoute =
  AuthenticatedStudentLessonLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedStudentLessonRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/history': typeof AuthenticatedStudentHistoryRoute
  '/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/lesson': typeof AuthenticatedStudentLessonRouteWithChildren
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/roadmap': typeof AuthenticatedStudentRoadmapRouteWithChildren
  '/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/roadmap/$moduleId': typeof AuthenticatedStudentRoadmapModuleIdRoute
  '/roadmap/': typeof AuthenticatedStudentRoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/history': typeof AuthenticatedStudentHistoryRoute
  '/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/lesson': typeof AuthenticatedStudentLessonRouteWithChildren
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/roadmap/$moduleId': typeof AuthenticatedStudentRoadmapModuleIdRoute
  '/roadmap': typeof AuthenticatedStudentRoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/_student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/_student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/_student/leaderboard': typeof AuthenticatedStudentLeaderboardRoute
  '/_authenticated/_student/lesson': typeof AuthenticatedStudentLessonRouteWithChildren
  '/_authenticated/_student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/_student/roadmap': typeof AuthenticatedStudentRoadmapRouteWithChildren
  '/_authenticated/_student/lesson/$lessonId': typeof AuthenticatedStudentLessonLessonIdRoute
  '/_authenticated/_student/roadmap/$moduleId': typeof AuthenticatedStudentRoadmapModuleIdRoute
  '/_authenticated/_student/roadmap/': typeof AuthenticatedStudentRoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/admin'
    | '/auth/login'
    | '/auth/register'
    | '/auth/'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/lesson'
    | '/profile'
    | '/roadmap'
    | '/lesson/$lessonId'
    | '/roadmap/$moduleId'
    | '/roadmap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/admin'
    | '/auth/login'
    | '/auth/register'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/lesson'
    | '/profile'
    | '/lesson/$lessonId'
    | '/roadmap/$moduleId'
    | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unauthorized'
    | '/_authenticated/_student'
    | '/_authenticated/admin'
    | '/auth/login'
    | '/auth/register'
    | '/auth/'
    | '/_authenticated/_student/dashboard'
    | '/_authenticated/_student/history'
    | '/_authenticated/_student/leaderboard'
    | '/_authenticated/_student/lesson'
    | '/_authenticated/_student/profile'
    | '/_authenticated/_student/roadmap'
    | '/_authenticated/_student/lesson/$lessonId'
    | '/_authenticated/_student/roadmap/$moduleId'
    | '/_authenticated/_student/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_student/roadmap': {
      id: '/_authenticated/_student/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedStudentRoadmapRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/profile': {
      id: '/_authenticated/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/lesson': {
      id: '/_authenticated/_student/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof AuthenticatedStudentLessonRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/leaderboard': {
      id: '/_authenticated/_student/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedStudentLeaderboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/history': {
      id: '/_authenticated/_student/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/dashboard': {
      id: '/_authenticated/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/roadmap/': {
      id: '/_authenticated/_student/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof AuthenticatedStudentRoadmapIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoadmapRoute
    }
    '/_authenticated/_student/roadmap/$moduleId': {
      id: '/_authenticated/_student/roadmap/$moduleId'
      path: '/$moduleId'
      fullPath: '/roadmap/$moduleId'
      preLoaderRoute: typeof AuthenticatedStudentRoadmapModuleIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoadmapRoute
    }
    '/_authenticated/_student/lesson/$lessonId': {
      id: '/_authenticated/_student/lesson/$lessonId'
      path: '/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentLessonRoute
    }
  }
}

interface AuthenticatedStudentLessonRouteChildren {
  AuthenticatedStudentLessonLessonIdRoute: typeof AuthenticatedStudentLessonLessonIdRoute
}

const AuthenticatedStudentLessonRouteChildren: AuthenticatedStudentLessonRouteChildren =
  {
    AuthenticatedStudentLessonLessonIdRoute:
      AuthenticatedStudentLessonLessonIdRoute,
  }

const AuthenticatedStudentLessonRouteWithChildren =
  AuthenticatedStudentLessonRoute._addFileChildren(
    AuthenticatedStudentLessonRouteChildren,
  )

interface AuthenticatedStudentRoadmapRouteChildren {
  AuthenticatedStudentRoadmapModuleIdRoute: typeof AuthenticatedStudentRoadmapModuleIdRoute
  AuthenticatedStudentRoadmapIndexRoute: typeof AuthenticatedStudentRoadmapIndexRoute
}

const AuthenticatedStudentRoadmapRouteChildren: AuthenticatedStudentRoadmapRouteChildren =
  {
    AuthenticatedStudentRoadmapModuleIdRoute:
      AuthenticatedStudentRoadmapModuleIdRoute,
    AuthenticatedStudentRoadmapIndexRoute:
      AuthenticatedStudentRoadmapIndexRoute,
  }

const AuthenticatedStudentRoadmapRouteWithChildren =
  AuthenticatedStudentRoadmapRoute._addFileChildren(
    AuthenticatedStudentRoadmapRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentLeaderboardRoute: typeof AuthenticatedStudentLeaderboardRoute
  AuthenticatedStudentLessonRoute: typeof AuthenticatedStudentLessonRouteWithChildren
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentRoadmapRoute: typeof AuthenticatedStudentRoadmapRouteWithChildren
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
  AuthenticatedStudentLeaderboardRoute: AuthenticatedStudentLeaderboardRoute,
  AuthenticatedStudentLessonRoute: AuthenticatedStudentLessonRouteWithChildren,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentRoadmapRoute:
    AuthenticatedStudentRoadmapRouteWithChildren,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
